### ISSUE TITLE
Sourceforge is actively blocked by many malware extensions in browsers.

### ISSUE THREAD

**Issue by photex** [SOCI/soci.github.com#1]
Is there anything I can do to lend a hand for this effort? Do you already own the domain? I'd be happy to spend some time getting this sorted so that people can find this awesome library without having to involve sourceforge. :)

**Comment by mloskot** [comment]
The https://github.com/SOCI/soci/tree/master/docs have been converted to Markdown.
Next, we need to convert/re-work https://github.com/SOCI/soci/tree/master/www to Markdown.
Finally, we need to
- Move site/docs content around (presumably to soci.github.com repo)
- Set up GH pages which I haven't had chance to learn/do properly.

So, there is room for contributions which would be welcome.
